channels:
  - conda-forge
  - bioconda
  - defaults
  - default
dependencies:
  - python=3.10.2
  - numpy==1.22.4
  - pandas==1.5.1
  - streamlit==1.16.0
  - seaborn==0.11.2
  - h5py=3.6.0
  - pyreadr=0.4.4
  - matplotlib=3.4.3
  - brewer2mpl=1.4.1
  - pip
  - tabulate=0.8.9
  - pip:
    - scikit-learn==1.0.2
    - st-annotated-text==3.0.0
    - torch==1.12.1
