channels:
  - conda-forge
  - bioconda
  - defaults
  - default
dependencies:
  - python=3.11.5
  - numpy=1.24.4
  - pandas=2.1.0
  - h5py=3.9.0
  - streamlit==1.26.0
  - matplotlib=3.7.2
  - brewer2mpl=1.4.1
  - scikit-learn=1.3.0
  - seaborn=0.11.2
  - st-annotated-text=4.0.1
  - torch=1.12.1
  


